version: '3'
services:
  app:
    container_name: "VolunteerMe"
    build: .
    ports:
      - "80:8000"
    environment:
      SECRET: "${SECRET}"
      DB_NAME: "${DB_NAME}"
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      DB_HOST: "${DB_HOST}"
